mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: true
external-controller: '0.0.0.0:19090'
secret: '123456'
external-ui: 'ui'
geox-url:
  geoip: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb'
  mmdb: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb'
proxies: []
proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - DIRECT
rules:
  - MATCH,GLOBAL
